- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes
  changed_when: false

- name: Install Docker (Linux)
  block:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker package
      package:
        name: docker-ce
        state: present
      when: ansible_os_family == "Debian"

    - name: Add user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker Desktop (MacOS)
      homebrew:
        name: docker
        state: present
      when: ansible_os_family == "Darwin"
  when: docker_check is failed

- name: Verify Docker installation
  command: docker --version
  register: docker_version
  changed_when: false

- name: Show Docker status
  debug:
    msg: "Docker {{ 'already installed' if docker_check is succeeded else 'was installed' }}: {{ docker_version.stdout }}"